"""Renders src/cuda/generated/<op>_<suffix>.cu from
src/cuda/templates/<op>.cu.tmpl for every Variant in variants.py.

Usage:
    python tools/kernelgen/generate.py          # (re)generate all variants
    python tools/kernelgen/generate.py --check  # verify committed output
                                                 # matches variants.py +
                                                 # templates/ without writing
                                                 # anything; exits 1 on drift

Templating uses the stdlib string.Template ($IDENT substitution) rather
than a third-party engine (no Jinja2 or similar is a dependency of this
project anywhere) and rather than str.format()/f-strings (the .cu.tmpl
bodies are full of literal C++ `{`/`}` that .format() would misparse as
format-spec delimiters).
"""
import argparse
import string
import sys
import tempfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from variants import VARIANTS  # noqa: E402

# tools/kernelgen/generate.py -> tools/kernelgen -> tools -> cmp_ext_turing
REPO_ROOT = Path(__file__).resolve().parents[2]
TEMPLATES_DIR = REPO_ROOT / "src" / "cuda" / "templates"
GENERATED_DIR = REPO_ROOT / "src" / "cuda" / "generated"

BANNER = (
    "// AUTO-GENERATED by tools/kernelgen/generate.py from\n"
    "// src/cuda/templates/{tmpl_name} -- DO NOT EDIT BY HAND.\n"
    "// Regenerate with: python tools/kernelgen/generate.py\n"
)


def render(variant):
    tmpl_name = f"{variant.op}.cu.tmpl"
    tmpl_path = TEMPLATES_DIR / tmpl_name
    if not tmpl_path.exists():
        raise FileNotFoundError(
            f"variants.py references op={variant.op!r} but {tmpl_path} does not exist"
        )
    template = string.Template(tmpl_path.read_text(encoding="utf-8"))
    # .substitute() (not .safe_substitute()) so a placeholder typo'd in the
    # template or missing from this call raises KeyError loudly, rather
    # than silently emitting a literal "$WHATEVER" into compiled source.
    # variant.params supplies every template-specific placeholder (BM/BN/
    # BK/STAGES for the WMMA kernels, BT_TILES/BT_COUT for Winograd, etc.)
    # -- SUFFIX is the one placeholder every template gets automatically.
    body = template.substitute(SUFFIX=variant.suffix, **variant.params)
    return BANNER.format(tmpl_name=tmpl_name) + body


def output_path(variant, out_dir):
    return out_dir / f"{variant.op}_{variant.suffix}.cu"


def generate(out_dir):
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for variant in VARIANTS:
        text = render(variant)
        path = output_path(variant, out_dir)
        path.write_text(text, encoding="utf-8", newline="\n")
        written.append(path)
    return written


def check():
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        generate(tmp_dir)

        drift = []
        for variant in VARIANTS:
            committed = output_path(variant, GENERATED_DIR)
            fresh = output_path(variant, tmp_dir)
            if not committed.exists():
                drift.append(f"missing:  {committed.relative_to(REPO_ROOT)}")
            elif committed.read_text(encoding="utf-8") != fresh.read_text(encoding="utf-8"):
                drift.append(f"stale:    {committed.relative_to(REPO_ROOT)}")

        # Catch committed files with no matching variants.py entry (e.g. a
        # variant that was removed but whose generated file wasn't deleted).
        expected = {output_path(v, GENERATED_DIR) for v in VARIANTS}
        if GENERATED_DIR.exists():
            for existing in sorted(GENERATED_DIR.glob("*.cu")):
                if existing not in expected:
                    drift.append(
                        f"orphaned: {existing.relative_to(REPO_ROOT)} "
                        "(no matching entry in variants.py)"
                    )

        if drift:
            print("src/cuda/generated/ is out of date with variants.py + templates/:",
                  file=sys.stderr)
            for line in drift:
                print(f"  {line}", file=sys.stderr)
            print("run: python tools/kernelgen/generate.py", file=sys.stderr)
            return 1

        print(f"OK -- {len(VARIANTS)} generated file(s) match variants.py + templates/.")
        return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check", action="store_true",
        help="verify committed src/cuda/generated/*.cu matches variants.py + "
             "templates/ without writing anything (nonzero exit on drift)",
    )
    args = parser.parse_args()

    if args.check:
        sys.exit(check())

    written = generate(GENERATED_DIR)
    for path in written:
        print(f"wrote {path.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
